//battingavgfun.cpp
#include <iostream>
using namespace std;
#include <stdlib.h>
void BattingAvg()  //declarator
{
int i, hits, atbats;
string name;
for (i=1; i<4; i++)
{
cout<<"What is the player's name? ";
cin>>name;
cout<<"How many hits does "<<name<<" have? ";
cin>>hits;
cout<<"How many at bats does "<<name<<" have? ";
cin>>atbats;
return (float)h/(float)ab;        //function body
}
int main()
{
BattingAvg();   //call to function
}
system("PAUSE");
return 0;
}

